[package]
edition = "2021"
name = "eo2"
resolver = "2"
version = "0.1.0"

[dependencies]
argh = "0.1"
az = "1"
bytemuck = "1"
clru = "0.6"
directories-next = "2"
eframe = { version = "0.19", features = ["serde"] }
egui = "0.19"
figment = { version = "0.10", features = ["toml"] }
image = { version = "0.24", path = "image", features = [
	"jpeg_rayon",
	"avif-decoder",
] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
toml = "0.5"
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[workspace]
members = [".", "image"]
