[package]
edition = "2021"
name = "eo2"
resolver = "2"
version = "0.1.0"

[dependencies]
argh = "0.1"
az = "1"
bytemuck = "1"
clru = { version = "0.6", git = "https://github.com/mattfbacon/clru-rs" }
directories-next = "2"
eframe = { version = "0.19", features = ["serde"] }
egui = "0.19"
figment = { version = "0.10", features = ["toml"] }
humansize = "2"
image = { version = "0.24", path = "image", features = [
	"jpeg_rayon",
	"avif-decoder",
] }
once_cell = "1"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
time = { version = "0.3", features = ["macros", "formatting", "local-offset"] }
toml = "0.5"
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[workspace]
members = [".", "image"]
